### ISSUE TITLE
[Enhancement] Scaling optimization on Windows high-resolution screen

### ISSUE THREAD

**Issue by Yana-Hangabina** [Apple-Music-Electron/Apple-Music-Electron#399]
The font that Apple Music Electron shows on my Windows (2K, 150% Scale) is too small to read. But when I change the compatibility setting of the EXE to system (enhanced), the font will be blurred.
Sincerely hope that a font size setting could be added or optimization on high-resolution screen could be considered!

**Comment by vapormusic** [comment]
What is the version of the app are you using right now ? On 3.0.0 , Go to preferences ( by clicking the your avatar ), then scroll down to Interface Scaling Multiplier, you can decrease it to suit your view

**Comment by Yana-Hangabina** [comment]
> What is the version of the app are you using right now ? On 3.0.0 , Go to preferences ( by clicking the your avatar ), then scroll down to Interface Scaling Multiplier, you can increase it to suit your view

! I'm using 3.0.0 and I'm not native English speaker (and the default font size is so small) so I didn't find it before, and thank you!! But now I got a new problem: 
I don't remember how I changed the theme but it looks like this, and, using this theme makes me unable to click the avatar to change the preference 😭

![Snipaste_2021-11-30_20-12-27.jpg](https://i.loli.net/2021/11/30/LXgUi3hujpTwEQ5.jpg)

**Comment by vapormusic** [comment]
Most likely you are being fallen back to using the (non-beta) site, due to an internet error. The app will still run, with limitations ( like you're currently facing).
An app restart should fix the issue:  
https://media.discordapp.net/attachments/843960846933688331/913736012235165716/unknown.png

**Comment by Yana-Hangabina** [comment]
I'm sure that the "useBetaSite" setting in config.json is right, but restart didn't fix it.
And when I reinstall it, I meet a NEW problem, if I click on Preferences, it will jump to Listen-Now, like this:
![GIF](https://i.imgur.com/cfsgA5C.gif)
I'm really puzzled >.<

**Comment by vapormusic** [comment]
> I'm sure that the "useBetaSite" setting in config.json is right, but restart didn't fix it. And when I reinstall it, I meet a NEW problem, if I click on Preferences, it will jump to Listen-Now, like this: ![GIF](https://camo.githubusercontent.com/3ec9fda3d55c04546d1cddf5b2c3bc9803472abdca41ff60d4276dec4cbaeb66/68747470733a2f2f692e696d6775722e636f6d2f636673674135432e676966) I'm really puzzled >.<

Something is really wrong with your current app, I've never faced this bug, please delete %Appdata%/AppleMusic folder.

**Comment by Yana-Hangabina** [comment]
It really works! Thank you!!!!
(last tiny enhancementable point: I've already changed Interface Scaling Multiplier to 1.5, but it seems like the right-click menu of 
 the tray bar icon is not multiplied)

**Comment by AstroNomen** [comment]
> I'm sure that the "useBetaSite" setting in config.json is right, but restart didn't fix it. And when I reinstall it, I meet a NEW problem, if I click on Preferences, it will jump to Listen-Now, like this: ![GIF](https://camo.githubusercontent.com/3ec9fda3d55c04546d1cddf5b2c3bc9803472abdca41ff60d4276dec4cbaeb66/68747470733a2f2f692e696d6775722e636f6d2f636673674135432e676966) I'm really puzzled >.<



> > I'm sure that the "useBetaSite" setting in config.json is right, but restart didn't fix it. And when I reinstall it, I meet a NEW problem, if I click on Preferences, it will jump to Listen-Now, like this: ![GIF](https://camo.githubusercontent.com/3ec9fda3d55c04546d1cddf5b2c3bc9803472abdca41ff60d4276dec4cbaeb66/68747470733a2f2f692e696d6775722e636f6d2f636673674135432e676966) I'm really puzzled >.<
> 
> Something is really wrong with your current app, I've never faced this bug, please delete %Appdata%/AppleMusic folder. (no reinstall needed)

I meet the same bug also, and I try to delete the %Appdata%/AppleMusic folder and restart the app, but I still can't open the Preferences. After trying to delete the folder and restart several times, I gived up. Now I can only edit the config.json file directly to change my preferences.
I have a suppose, maybe this bug is language related, cause he and I both are Chinese user?

**Comment by vapormusic** [comment]
This should be fixed by  #410 (url)

> > I'm sure that the "useBetaSite" setting in config.json is right, but restart didn't fix it. And when I reinstall it, I meet a NEW problem, if I click on Preferences, it will jump to Listen-Now, like this: ![GIF](https://camo.githubusercontent.com/3ec9fda3d55c04546d1cddf5b2c3bc9803472abdca41ff60d4276dec4cbaeb66/68747470733a2f2f692e696d6775722e636f6d2f636673674135432e676966) I'm really puzzled >.<
> 
> > > I'm sure that the "useBetaSite" setting in config.json is right, but restart didn't fix it. And when I reinstall it, I meet a NEW problem, if I click on Preferences, it will jump to Listen-Now, like this: ![GIF](https://camo.githubusercontent.com/3ec9fda3d55c04546d1cddf5b2c3bc9803472abdca41ff60d4276dec4cbaeb66/68747470733a2f2f692e696d6775722e636f6d2f636673674135432e676966) I'm really puzzled >.<
> > 
> > 
> > Something is really wrong with your current app, I've never faced this bug, please delete %Appdata%/AppleMusic folder. (no reinstall needed)
> 
> I meet the same bug also, and I try to delete the %Appdata%/AppleMusic folder and restart the app, but I still can't open the Preferences. After trying to delete the folder and restart several times, I gived up. Now I can only edit the config.json file directly to change my preferences. I have a suppose, maybe this bug is language related, cause he and I both are Chinese user?
